global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "weather-app"
    static_configs:
      - targets: ["weather:8000"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://weather:8000/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: "weather-metrics"
    static_configs:
      - targets: ["weather:8000"]
    metrics_path: /metrics
       
